USE [master]
GO

/****** Object:  Database [Atena]    Script Date: 05/07/2023 22:37:06 ******/
CREATE DATABASE [Atena]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Atena', FILENAME = N'C:\Users\roger\Atena.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Atena_log', FILENAME = N'C:\Users\roger\Atena_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Atena].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Atena] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Atena] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Atena] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Atena] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Atena] SET ARITHABORT OFF 
GO

ALTER DATABASE [Atena] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Atena] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Atena] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Atena] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Atena] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Atena] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Atena] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Atena] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Atena] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Atena] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Atena] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Atena] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Atena] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Atena] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Atena] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Atena] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Atena] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Atena] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Atena] SET  MULTI_USER 
GO

ALTER DATABASE [Atena] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Atena] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Atena] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Atena] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Atena] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Atena] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Atena] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Atena] SET  READ_WRITE 
GO


